In [2]:
import numpy as np

# m function
def m(buff, args=""):
    """_summary_
        A print() function wrapper for typing less words
    
    Args:
        buff (_type_): _description_
        args (str, optional): _description_. Defaults to "".
    """
    print(buff,args)


In [3]:
# creating an array
ara = np.array(
    [[1,2,3],
    [4,5,6]]
)
m(ara)
m(ara.ndim)         # dimensions
m(ara.shape)        # shape (rxc) [ r = rows, c = columns ]
m(type(ara))        # numpy.ndarray
m(ara.data)
# m(help(ara.data))
m(ara.dtype)        # array data type
m(ara.itemsize)     # occupied memory by each item
m(ara.size)        

[[1 2 3]
 [4 5 6]] 
2 
(2, 3) 
<class 'numpy.ndarray'> 
int32 
4 
6 


In [ ]:
arab = np.array(
    [[1,2,3],
    [4,5,6]],
    dtype=np.float32
)
arac = np.array(
    [[1,2,3],
    [4,5,6]],
    dtype=np.float64
)
arad = np.array(
    [[1,2,3],
    [4,5,6]],
    dtype=np.complex64
)
arae = np.array(
    [[1,2,3],
    [4,5,6]],
    dtype=np.complex128
)

m(arab.itemsize)    # float 32 = 4
m(arac.itemsize)    # float 64 = 8
m(arad.itemsize)    # complex 64 = 8
m(arae.itemsize)    # complex 128 = 16

m(arab)
m(arac)
m(arad)
m(arae)


In [16]:
# sum
m(np.sum(ara, axis=1))
m(np.sum(ara, axis=0))
m(np.amin(ara))
m(np.mean(ara))
m(np.median(ara))

[ 6 15] 
[5 7 9] 
1 
3.5 
3.5 


In [20]:
m(np.std(ara))
m(np.std(ara, axis=0))
m(np.std(ara, axis=1))

1.707825127659933 
[1.5 1.5 1.5] 
[0.81649658 0.81649658] 


In [22]:
m(np.average(ara))
m(help(np.average))

3.5 
Help on function average in module numpy:

average(a, axis=None, weights=None, returned=False)
    Compute the weighted average along the specified axis.
    
    Parameters
    ----------
    a : array_like
        Array containing data to be averaged. If `a` is not an array, a
        conversion is attempted.
    axis : None or int or tuple of ints, optional
        Axis or axes along which to average `a`.  The default,
        axis=None, will average over all of the elements of the input array.
        If axis is negative it counts from the last to the first axis.
    
        .. versionadded:: 1.7.0
    
        If axis is a tuple of ints, averaging is performed on all of the axes
        specified in the tuple instead of a single axis or all the axes as
        before.
    weights : array_like, optional
        An array of weights associated with the values in `a`. Each value in
        `a` contributes to the average according to its associated weight.
        The weights arr

In [35]:
np.percentile(ara,0,0)

array([1., 2., 3.])

In [42]:
np.ptp(ara,1)

array([2, 2])

In [46]:
res = ara.reshape(3,2)
m(ara)
m(res)

[[1 2 3]
 [4 5 6]] 
[[1 2]
 [3 4]
 [5 6]] 
